const state={user:null,page:'landing',questions:[],loaded:false,mode:null,year:'',subject:'',lesson:'',count:10,minutes:15,index:0,answers:{},skipped:new Set(),revealed:new Set(),timer:null,remaining:0,authMode:'login',installPrompt:null,result:null};
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const api=async(path,opts={})=>{try{const r=await fetch('/api'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const d=await r.json().catch(()=>({}));return r.ok?d:{...d,error:d.error||`تعذر تنفيذ الطلب (${r.status})`,status:r.status}}catch{return{error:'تعذر الاتصال بالخادم. حاول مرة أخرى.'}}};
const toast=t=>{const x=document.createElement('div');x.className='toast';x.setAttribute('role','status');x.setAttribute('aria-live','polite');x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),3500)};
function shuffle(a){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r}
function saveProgress(){if(state.page!=='examCards')return;localStorage.setItem('fahem_exam_progress',JSON.stringify({questions:state.questions,year:state.year,subject:state.subject,lesson:state.lesson,count:state.count,minutes:state.minutes,index:state.index,answers:state.answers,skipped:[...state.skipped],remaining:state.remaining}))}
function clearProgress(){localStorage.removeItem('fahem_exam_progress')}
function restoreProgress(){const raw=localStorage.getItem('fahem_exam_progress');if(!raw)return false;try{const p=JSON.parse(raw);if(!p.questions?.length)return false;state.questions=p.questions;state.year=p.year||'';state.subject=p.subject||'';state.lesson=p.lesson||'';state.count=p.count||p.questions.length;state.minutes=p.minutes||15;state.index=Math.min(p.index||0,p.questions.length-1);state.answers=p.answers||{};state.skipped=new Set(p.skipped||[]);state.remaining=p.remaining||state.minutes*60;state.mode='exam';state.page='examCards';return true}catch{return false}}
function focusHeading(){requestAnimationFrame(()=>{const h=document.querySelector('main h1,[data-autofocus]');if(h){h.setAttribute('tabindex','-1');h.focus({preventScroll:true})}})}
function shell(content){app.innerHTML=`<header class="site-header"><button class="brand" aria-label="العودة إلى الصفحة الرئيسية" data-action="go('landing')"><span class="brand-mark" aria-hidden="true">ب</span><span><b>بنك أسئلة الكتاب المدرسي</b><small>راجع بفهم واختبر نفسك</small></span></button><div class="header-actions">${state.user?`<span class="user-name">${esc(state.user.name||state.user.email)}</span><button class="text-btn" data-action="logout()">خروج</button>`:''}</div></header><main class="page-wrap" id="main-content" tabindex="-1">${content}</main><footer class="site-footer">بنك أسئلة الكتاب المدرسي · تعلّم خطوة بخطوة</footer>`;window.scrollTo({top:0,behavior:'instant'});focusHeading()}
function landing(){shell(`<section class="landing"><div class="landing-copy"><span class="kicker">منصة الطالب</span><h1>كتابك في إيدك.<br><em>وفهمك في تقدم.</em></h1><p>مراجعة منظمة واختبارات قصيرة من أسئلة الكتاب المدرسي، في تجربة بسيطة تركز على ما تحتاجه.</p><div class="landing-note"><span aria-hidden="true">⌁</span><span>اختر طريقك وابدأ من الدرس الذي تريده.</span></div><div class="trust-strip" aria-label="مميزات المنصة"><span>أسئلة من الكتاب</span><span>شرح نموذجي</span><span>اختبارات مؤقتة</span></div></div><div class="choice-grid"><button class="choice-card review-card" aria-label="ابدأ مراجعة أسئلة الكتاب" data-action="startJourney('review')"><span class="choice-icon" aria-hidden="true">▤</span><span class="choice-label">المراجعة</span><strong>ذاكر السؤال والإجابة</strong><small>بطاقات تعليمية، إجابة نموذجية، وشرح مختصر.</small><b class="choice-arrow">ابدأ المراجعة ←</b></button><button class="choice-card exam-card" aria-label="أنشئ اختبارًا من أسئلة الكتاب" data-action="startJourney('exam')"><span class="choice-icon" aria-hidden="true">✦</span><span class="choice-label">اختبر نفسك</span><strong>أنشئ اختبارك بنفسك</strong><small>اختر الدرس والوقت وعدد الأسئلة ثم ابدأ.</small><b class="choice-arrow">أنشئ اختبارًا ←</b></button></div></section>`)}
function auth(){const register=state.authMode==='register';shell(`<section class="auth-page"><div class="auth-intro"><span class="kicker">خطوة واحدة وتبدأ</span><h1>${register?'أنشئ حسابك':'مرحبًا بعودتك'}</h1><p>${register?'احفظ تقدمك وابدأ مراجعة منهجك.':'سجّل دخولك لتصل إلى أسئلة صفك ومحاولاتك.'}</p></div><section class="auth-box"><div class="auth-box-head"><span class="brand-mark" aria-hidden="true">ب</span><div><h2>${register?'إنشاء حساب طالب':'تسجيل الدخول'}</h2><p>${register?'بياناتك تساعدنا نعرض لك منهجك.':'استخدم بريدك وكلمة المرور.'}</p></div></div>${register?`<label for="name">الاسم<input id="name" placeholder="اكتب اسمك" autocomplete="name"></label>`:''}<label for="email">البريد الإلكتروني<input id="email" type="email" placeholder="name@example.com" autocomplete="email"></label>${register?`<label for="stage">المرحلة الدراسية<select id="stage"><option value="">اختر المرحلة</option><option>ابتدائي</option><option>إعدادي</option><option>ثانوي</option></select></label><label for="year">السنة الدراسية<select id="year"><option value="">اختر المرحلة أولًا</option></select></label>`:''}<label for="password">كلمة المرور<input id="password" type="password" placeholder="8 أحرف على الأقل" autocomplete="current-password"></label><button class="primary-btn full" data-action="submitAuth()">${register?'إنشاء الحساب':'تسجيل الدخول'} <span aria-hidden="true">←</span></button><button class="link-btn full" data-action="setAuthMode('${register?'login':'register'}')">${register?'لدي حساب بالفعل — تسجيل الدخول':'ليس لدي حساب — إنشاء حساب'}</button></section></section>`)}
function yearPicker(){const years=[...new Set(state.questions.map(q=>q.school_year).filter(Boolean))];const fallback=state.user?.school_year?[state.user.school_year]:['الصف الثاني الثانوي'];shell(`<section class="journey-page"><button class="back-btn" data-action="go('landing')">→ رجوع</button><div class="section-heading"><span class="kicker">${state.mode==='review'?'المراجعة':'اختبر نفسك'}</span><h1>اختر السنة الدراسية</h1><p>سنجهز لك محتوى الكتاب المناسب لصفك.</p></div><div class="year-grid">${(years.length?years:fallback).map(y=>`<button class="year-card" aria-label="اختيار ${esc(y)}" data-action="chooseYear('${esc(y)}')"><span>السنة الدراسية</span><strong>${esc(y)}</strong><b>عرض المحتوى ←</b></button>`).join('')}</div></section>`)}
function setupPage(mode){const qs=state.questions.filter(q=>!state.year||q.school_year===state.year);const subjects=[...new Set(qs.map(q=>q.subject).filter(Boolean))];const subjectQs=qs.filter(q=>!state.subject||q.subject===state.subject);const lessons=[...new Set(subjectQs.map(q=>q.lesson||q.chapter).filter(Boolean))];const review=mode==='review';const available=Math.max(subjectQs.length,5);const counts=[5,10,15,20,30,50].filter(n=>n<=available);shell(`<section class="journey-page"><button class="back-btn" data-action="go('yearPicker')">→ تغيير السنة</button><div class="section-heading"><span class="kicker">${review?'بطاقات المراجعة':'إعداد الاختبار'}</span><h1>${review?'حدد نقطة البداية':'صمّم اختبارك'}</h1><p>${review?'اختر المادة ثم الدرس وابدأ في تقليب البطاقات التعليمية.':'اختر المادة والدرس والوقت وعدد الأسئلة كما تحب.'}</p></div><section class="setup-box"><div class="selected-year"><span>السنة المختارة</span><strong>${esc(state.year)}</strong></div><label for="subject">المادة<select id="subject"><option value="">${review?'كل المواد':'كل المواد'}</option>${subjects.map(x=>`<option value="${esc(x)}" ${x===state.subject?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label for="lesson">الدرس<select id="lesson"><option value="">${review?'كل الدروس':'كل المنهج'}</option>${lessons.map(x=>`<option value="${esc(x)}" ${x===state.lesson?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label for="count">عدد الأسئلة<select id="count">${counts.map(n=>`<option value="${n}" ${n===state.count?'selected':''}>${n} أسئلة</option>`).join('')}</select></label>${review?'':`<label for="minutes">وقت الاختبار<select id="minutes"><option value="5">5 دقائق</option><option value="10">10 دقائق</option><option value="15" ${state.minutes===15?'selected':''}>15 دقيقة</option><option value="30">30 دقيقة</option></select></label>`}<p class="setup-hint">${subjectQs.length} سؤال متاح وفق اختياراتك الحالية.</p><button class="primary-btn full" data-action="beginStudy('${mode}')">${review?'ابدأ المراجعة ←':'ابدأ الاختبار ←'}</button></section></section>`)}
function beginStudy(mode){state.subject=$('#subject')?.value||'';state.lesson=$('#lesson')?.value||'';state.count=Number($('#count')?.value||5);state.minutes=Number($('#minutes')?.value||15);const pool=state.questions.filter(q=>(!state.year||q.school_year===state.year)&&(!state.subject||q.subject===state.subject)&&(!state.lesson||(q.lesson||q.chapter)===state.lesson));if(!pool.length)return toast('لا توجد أسئلة متاحة بهذا الاختيار');state.questions=shuffle(pool).slice(0,state.count);state.mode=mode;state.index=0;state.answers={};state.skipped=new Set();state.revealed=new Set();state.remaining=state.minutes*60;clearInterval(state.timer);state.page=mode==='review'?'reviewCards':'examCards';if(mode==='exam')saveProgress();render()}
function questionCard(q,i,exam=false){const answered=state.answers[q.id],shown=state.revealed.has(q.id);const options=(q.options||[]).map((o,n)=>`<label class="option"><input type="radio" name="q-${q.id}" value="${esc(o)}" ${answered===o?'checked':''} data-question="${q.id}"><span>${esc(o)}</span></label>`).join('');const answer=shown?`<div class="answer-box"><strong>الإجابة النموذجية</strong><p>${esc(q.correct_answer||'تحتاج هذه الإجابة إلى مراجعة يدوية.')}</p>${q.explanation?`<small>${esc(q.explanation)}</small>`:''}</div>`:'';return `<article class="study-card ${exam?'exam-question':''}" id="q-${q.id}"><div class="card-top"><span class="card-number">${String(i+1).padStart(2,'0')}</span><span class="card-tag">${esc(q.lesson||q.chapter||'الدرس')}</span></div><h2 id="question-${q.id}">${esc(q.prompt)}</h2>${exam?`<fieldset class="options" aria-labelledby="question-${q.id}"><legend class="sr-only">اختر إجابة للسؤال ${i+1}</legend>${options}</fieldset>`:`<button class="reveal-btn" aria-expanded="${shown}" data-action="toggleAnswer(${q.id})">${shown?'إخفاء الإجابة':'إظهار الإجابة'} <span aria-hidden="true">${shown?'↑':'↓'}</span></button>${answer}`}</article>`}
function reviewCards(){shell(`<section class="study-page"><div class="study-head"><button class="back-btn" data-action="go('landing')">→ البداية</button><div><span class="kicker">مراجعة بطاقات</span><h1>${esc(state.year)}</h1></div><span class="progress-pill">${state.questions.length} بطاقة</span></div><div class="cards-list">${state.questions.map((q,i)=>questionCard(q,i)).join('')}</div></section>`)}
function examCards(){const q=state.questions[state.index];if(!q)return resultPage();const mins=Math.floor(state.remaining/60),secs=String(state.remaining%60).padStart(2,'0'),answered=Object.keys(state.answers).length;const warning=state.remaining<=60?' timer-warning':'';shell(`<section class="study-page"><div class="study-head"><button class="back-btn" data-action="confirmExit()">→ خروج</button><div><span class="kicker">اختبار ${esc(state.year)}</span><h1>أجب بهدوء</h1></div><span class="timer-pill${warning}" role="timer" aria-live="polite">${mins}:${secs}</span></div><div class="exam-progress" aria-live="polite">السؤال ${state.index+1} من ${state.questions.length} · تمت الإجابة عن ${answered} · المتروك ${state.skipped.size}</div><div class="progress-bar" aria-hidden="true"><span style="width:${((state.index+1)/state.questions.length)*100}%"></span></div><div class="cards-list">${questionCard(q,state.index,true)}</div><div class="exam-nav"><button class="secondary-btn" data-action="examPrevious()" ${state.index?'':'disabled'}>السابق</button>${state.index===state.questions.length-1?`<button class="primary-btn" data-action="submitExam()">إنهاء الاختبار</button>`:`<button class="primary-btn" data-action="examNext()">التالي</button>`}</div></section>`);if(!state.timer)state.timer=setInterval(()=>{state.remaining--;saveProgress();if(state.remaining<=0){clearInterval(state.timer);state.timer=null;toast('انتهى الوقت، جارٍ حساب النتيجة');submitExam()}else{$('.timer-pill').textContent=`${Math.floor(state.remaining/60)}:${String(state.remaining%60).padStart(2,'0')}`;$('.timer-pill').classList.toggle('timer-warning',state.remaining<=60)}},1000)}
function examNext(){const q=state.questions[state.index];if(!state.answers[q.id]){state.skipped.add(q.id);if(!confirm('لم تجب عن هذا السؤال. هل تريد المتابعة دون إجابة؟'))return}if(state.index<state.questions.length-1){state.index++;saveProgress();render()}}
function examPrevious(){if(state.index>0){state.index--;saveProgress();render()}}
async function submitExam(){clearInterval(state.timer);state.timer=null;const total=state.questions.filter(q=>q.type!=='essay').length;const score=state.questions.reduce((n,q)=>n+(q.type!=='essay'&&state.answers[q.id]===q.correct_answer?1:0),0);const details=state.questions.map(q=>({id:q.id,prompt:q.prompt,selected:state.answers[q.id]||'',correct:q.correct_answer||'',correctAnswer:state.answers[q.id]===q.correct_answer}));const result=state.user?await api('/attempts',{method:'POST',body:JSON.stringify({mode:'mock',question_ids:state.questions.map(q=>q.id),answers:state.answers})}):{score,total};state.result={...result,score:result.score??score,total:result.total??total,details};clearProgress();state.page='result';render()}
function resultPage(){const r=state.result||{},details=r.details||[],wrong=details.filter(d=>!d.correctAnswer);shell(`<section class="result-page" aria-live="polite"><span class="result-icon" aria-hidden="true">✓</span><span class="kicker">انتهى الاختبار</span><h1>نتيجتك جاهزة</h1><div class="score-box"><strong>${r.score??0}</strong><span>من ${r.total??state.questions.length}</span></div><div class="result-summary"><span>الصحيح: ${details.filter(d=>d.correctAnswer).length}</span><span>الخاطئ أو المتروك: ${wrong.length}</span></div><p>${wrong.length?'راجع الأسئلة المظللة أدناه لتثبيت فهمك.':'أحسنت، إجاباتك كلها صحيحة في هذا الاختبار.'}</p>${details.length?`<div class="result-details"><h2>مراجعة الإجابات</h2>${details.map((d,i)=>`<article class="result-item ${d.correctAnswer?'is-correct':'is-wrong'}"><strong>${i+1}. ${esc(d.prompt)}</strong><span>${d.selected?`إجابتك: ${esc(d.selected)}`:'لم تتم الإجابة'}</span>${!d.correctAnswer&&d.correct?`<span>الصحيح: ${esc(d.correct)}</span>`:''}</article>`).join('')}</div>`:''}<div class="result-actions"><button class="primary-btn" data-action="go('landing')">العودة للبداية</button><button class="secondary-btn" data-action="startJourney('review')">راجع البطاقات</button></div></section>`)}
function toggleAnswer(id){state.revealed.has(id)?state.revealed.delete(id):state.revealed.add(id);render()}
function startJourney(mode){state.mode=mode;state.page='yearPicker';loadQuestions().then(render)}
async function loadQuestions(){if(state.loaded)return;const r=await api('/questions');if(!Array.isArray(r.questions)){toast(r.error||'تعذر تحميل الأسئلة');return}state.questions=r.questions;state.loaded=true}
function setAuthMode(mode){state.authMode=mode;auth()}
async function submitAuth(){const name=$('#name')?.value.trim()||'',email=$('#email')?.value.trim()||'',password=$('#password')?.value||'',educational_stage=$('#stage')?.value||'',school_year=$('#year')?.value||'',register=state.authMode==='register';if(!email||!password)return toast('أدخل البريد الإلكتروني وكلمة المرور');if(register&&(!name||!educational_stage||!school_year))return toast('أكمل الاسم والمرحلة والسنة الدراسية');const r=await api('/auth',{method:'POST',body:JSON.stringify({name,email,password,educational_stage,school_year})});if(!r.user)return toast(r.error||'تعذر الدخول. راجع البيانات');state.user=r.user;localStorage.setItem('mr_user',JSON.stringify(r.user));state.page=state.afterAuth||'landing';state.afterAuth=null;await loadQuestions();render()}
async function logout(){await api('/auth/logout',{method:'POST'});localStorage.removeItem('mr_user');clearProgress();state.user=null;state.loaded=false;state.questions=[];clearInterval(state.timer);state.page='landing';render()}
function confirmExit(){if(confirm('هل تريد الخروج من الاختبار؟ ستُحفظ إجاباتك مؤقتًا ويمكن استئناف الاختبار عند العودة.')){saveProgress();clearInterval(state.timer);state.timer=null;state.page='landing';render()}}
function chooseYear(y){state.year=y;state.subject='';state.lesson='';state.page=state.mode==='review'?'reviewSetup':'examSetup';render()}
function go(page){if(page==='yearPicker'){state.page='yearPicker';return loadQuestions().then(render)}state.page=page;render()}
function render(){if(state.page==='landing')return landing();if(state.page==='auth')return auth();if(state.page==='yearPicker')return yearPicker();if(state.page==='reviewSetup')return setupPage('review');if(state.page==='examSetup')return setupPage('exam');if(state.page==='reviewCards')return reviewCards();if(state.page==='examCards')return examCards();if(state.page==='result')return resultPage();return landing()}
function boot(){if(localStorage.getItem('fahem_theme')==='dark')document.documentElement.classList.add('dark');api('/auth/me').then(async r=>{if(r.user){state.user=r.user;await loadQuestions()}else localStorage.removeItem('mr_user');const resumed=restoreProgress();if(resumed&&!confirm('يوجد اختبار محفوظ. هل تريد استئنافه؟')){clearProgress();state.page='landing'}render()})}
document.addEventListener('click',e=>{const t=e.target.closest('[data-action]');if(!t)return;const a=t.dataset.action,m=a.match(/^([A-Za-z_$][\w$]*)\((.*)\)$/s);if(!m)return;const fn=window[m[1]];if(typeof fn!=='function')return;const args=m[2].trim()?m[2].split(',').map(v=>{v=v.trim();return(v.startsWith("'")&&v.endsWith("'"))||(v.startsWith('"')&&v.endsWith('"'))?v.slice(1,-1):Number.isNaN(Number(v))?v:Number(v)}):[];e.preventDefault();fn(...args)});
document.addEventListener('change',e=>{if(e.target.id==='stage'){const y=$('#year');const m={ابتدائي:['الصف الأول الابتدائي','الصف الثاني الابتدائي','الصف الثالث الابتدائي','الصف الرابع الابتدائي','الصف الخامس الابتدائي','الصف السادس الابتدائي'],إعدادي:['الصف الأول الإعدادي','الصف الثاني الإعدادي','الصف الثالث الإعدادي'],ثانوي:['الصف الأول الثانوي','الصف الثاني الثانوي','الصف الثالث الثانوي']};if(y)y.innerHTML='<option value="">اختر المرحلة أولًا</option>'+(m[e.target.value]||[]).map(x=>`<option>${x}</option>`).join('')}if(e.target.id==='subject'){state.subject=e.target.value;state.lesson='';render()}});
document.addEventListener('change',e=>{if(e.target.matches('[data-question]')){state.answers[e.target.dataset.question]=e.target.value;state.skipped.delete(Number(e.target.dataset.question));saveProgress();const p=e.target.closest('.study-card');p?.classList.add('just-answered');setTimeout(()=>p?.classList.remove('just-answered'),500)}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});boot();
Object.assign(window,{startJourney,chooseYear,beginStudy,toggleAnswer,examNext,examPrevious,submitExam,confirmExit,go,logout,setAuthMode,submitAuth});
